### ISSUE TITLE
Symbol’s function definition is void: --if-let

### ISSUE THREAD

**Issue by efermi** [brotzeitmacher/arch-packer#2]
When executing the `arch-packer-list-packages` command the following error occurs:
```
error in process sentinel: async-handle-result: Symbol’s function definition is void: --if-let
error in process sentinel: Symbol’s function definition is void: --if-let
```
The command itself doesn't produce any result.

**Comment by brotzeit** [comment]
That's because I forgot to add dash as dependency. I didn't use the package for some time and it seems I have to fix some other things too. I will take a look at it.

**Comment by brotzeit** [comment]
Does it work ?

**Comment by efermi** [comment]
Yes, thank you
